---
title: "Anna exploration"
output: html_document
date: "2023-04-14"
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r include=FALSE}
  # data on voleteer atorneys
attorneys_data <- read_csv("data/DataFest_2023_Data/attorneys.csv")
  # time sheet data 
attorneytimeentries <- read_csv("data/DataFest_2023_Data/attorneytimeentries.csv")
  # client 
clients <- read_csv("data/DataFest_2023_Data/clients.csv")

questionposts <- read_csv("data/DataFest_2023_Data/questionposts.csv")

questions <- read_csv("data/DataFest_2023_Data/questions.csv")

##

statesites <- read_csv("data/DataFest_2023_Data/statesites.csv")

  # Legal Services Corporation universal catagories for all states
categories <- read_csv("data/DataFest_2023_Data/categories.csv")
  # subcatagories spesific to states
subcategories <- read_csv("data/DataFest_2023_Data/statesites.csv")
```

```{r}
states_over_2400 <-
  questions %>%
  group_by(StateAbbr) %>%
  filter(AskedOnUtc >= "2020-01-01 00:00:00") %>% 
  count(StateAbbr) %>%
  filter(n >= 2400) %>%
  pull(StateAbbr)

relevant_states <-
  questions %>% 
  group_by(StateAbbr) %>% 
  summarize(start = min(AskedOnUtc)) %>%
  filter(
    start < "2020-01-01 00:00:00",
    StateAbbr %in% states_over_2400
  ) %>%
  pull(StateAbbr)
```

```{r}
questionposts %>%
  filter(str_detect(PostText, "transgender")) %>%
  left_join(questions, by = "QuestionUno") %>%
  group_by(Category, Subcategory) %>%
  summarize()

```

```{r}
questions%>% 
  filter(StateAbbr=='MA') %>% 
  count(Subcategory) %>% 
  arrange(desc(n))

questions%>% 
  count(Subcategory) %>% 
  arrange(desc(n))
```

```{r}
questions%>% 
  filter(StateAbbr=='MA') %>% 
  count(Category) %>% 
  arrange(desc(n))

attorneys_data %>% 
  group_by(StateAbbr) %>% 
  count() %>% 
  arrange(desc(n))
```

Explore state income cut off qualifications

```{r}
statesites %>% 
  arrange(desc(BaseIncomeLimit))

statesites %>% 
  arrange(desc(IncomeMultiplier))

statesites %>% 
  arrange(desc(AllowedAssets))

statesites %>% 
  filter(StateAbbr=='PA')
```

```{r}
questions %>% 
  filter(StateAbbr=='TX', ) %>% 
  count(Subcategory) %>% 
  arrange(desc(n))

subcategories %>% 
  group_by(StateAbbr)
```

Create the mega data set!

```{r}
questions %>%
  left_join(clients, by = c("AskedByClientUno" = "ClientUno", "StateAbbr")) %>%
  group_by(StateAbbr) %>%
  mutate(
    is_null = 1 * (TakenByAttorneyUno == "NULL"),
  ) %>%
  count(is_null) %>%
  pivot_wider(
    names_from = "is_null",
    names_prefix = "null",
    values_from = "n"
  ) %>%
  mutate(
    null_percent = null1 / (null0 + null1)
  ) %>%
  arrange(null_percent)


```

```{r}
questions%>% 
  filter(
    StateAbbr=='TX',
    # TakenByAttorneyUno == "NULL"
    ) %>%
  # mutate(
  #   is_null = (TakenByAttorneyUno == "NULL"),
  # ) %>%  
  ggplot() +
  geom_histogram(aes(x = AskedOnUtc, alpha = 0.2), bins = 72) +
  geom_histogram(data = . %>% filter(TakenByAttorneyUno == "NULL"), aes(x = AskedOnUtc, fill = StateAbbr), bins = 72)
  

```

```{r}
questions%>% 
  filter(
    StateAbbr=='FL',
    # TakenByAttorneyUno == "NULL"
    ) %>%
  # mutate(
  #   is_null = (TakenByAttorneyUno == "NULL"),
  # ) %>%  
  ggplot() +
  geom_histogram(aes(x = AskedOnUtc, alpha = 0.2), bins = 72) +
  geom_histogram(data = . %>% filter(TakenByAttorneyUno == "NULL"), aes(x = AskedOnUtc, fill = StateAbbr), bins = 72)
  
```

```{r}
questions%>% 
  filter(
    #StateAbbr== c('TX', 'FL','GA','AZ','IN','CA'),
    # TakenByAttorneyUno == "NULL"
    ) %>%
  # mutate(
  #   is_null = (TakenByAttorneyUno == "NULL"),
  # ) %>%  
  ggplot() +
  geom_histogram(aes(x = AskedOnUtc, alpha = 0.2), bins = 72) +
  geom_histogram(data = . %>% filter(TakenByAttorneyUno != "NULL"), aes(x = AskedOnUtc, fill = StateAbbr), bins = 72) +
  facet_wrap(facets =  vars(StateAbbr))
```

```{r}
questions%>% 
  filter(
    #StateAbbr== c('TX', 'FL','GA','AZ','IN','CA'),
    # TakenByAttorneyUno == "NULL",
    AskedOnUtc > '2020-01-01 00:00:00.000
'
    ) %>%
  # mutate(
  #   is_null = (TakenByAttorneyUno == "NULL"),
  # ) %>%  
  ggplot() +
  geom_histogram(aes(x = AskedOnUtc, alpha = 0.2), bins = 24) +
  geom_histogram(data = . %>% filter(TakenByAttorneyUno != "NULL"), aes(x = AskedOnUtc, fill = StateAbbr), bins = 24) +
  facet_wrap(facets =  vars(StateAbbr)) 
```

```{r}
questions%>% 
  filter(
    StateAbbr== c('TN', 'WI', 'FL', 'NC', 'MO', 'VA', 'NY', 'SC', 'IL', 'MA', 'IN', 'TX', 'OK', 'AZ', 'GA'),
    # TakenByAttorneyUno == "NULL",
    AskedOnUtc > '2020-01-01 00:00:00.000
'
    ) %>%
  # mutate(
  #   is_null = (TakenByAttorneyUno == "NULL"),
  # ) %>%  
  ggplot() +
  geom_histogram(aes(x = AskedOnUtc, alpha = 0.2), bins = 24) +
  geom_histogram(data = . %>% filter(TakenByAttorneyUno != "NULL"), aes(x = AskedOnUtc, fill = StateAbbr), bins = 24) +
  facet_wrap(facets =  vars(StateAbbr)) 
```

```{r}
byDayattorneytime <- 
  attorneytimeentries %>%
  separate(EnteredOnUtc, into = "EnteredOnUtc", sep = 7, extra = "drop") %>% 
  #separate(EnteredOnUtc, into = "EnteredOnUtc", sep = " ", extra = "drop") %>% 
  group_by(StateAbbr, EnteredOnUtc) %>%
  summarize(Hours = sum(Hours)) %>% 
  ungroup()

byDayattorneytime
```

```{r}
byDayattorneytime %>%
  filter(StateAbbr == c('TX', 'FL')) %>% 
  ggplot() +
  geom_bar(aes(
    x = EnteredOnUtc,
    y = Hours,
    color = StateAbbr
  )) +
  facet_wrap(facets =  vars(StateAbbr))

# geom_point(aes(
#   data = byDayattorneytime %>% filter(StateAbbr == c('TX', 'FL')),
#     x = EnteredOnUtc,
#     y = Hours
#   ))
# og code from brook
# attorneytimeentries %>%
#   separate(EnteredOnUtc, into = "EnteredOnUtc", sep = " ", extra = "drop") %>% 
#   group_by(EnteredOnUtc) %>%
#   summarize(Hours = sum(Hours)) %>% 
#   ggplot() +
#   geom_col(aes(
#     x = EnteredOnUtc,
#     y = Hours
#   )) 
```

```{r}
questions%>% 
  filter(
    StateAbbr == c('TX', 'FL')
    ) %>%
 
  ggplot() +
  geom_histogram(aes(x = AskedOnUtc, alpha = 0.2), bins = 72) +
  geom_histogram(data = . %>% filter(TakenByAttorneyUno != "NULL"), aes(x = AskedOnUtc, fill = StateAbbr), bins = 72)  +
  # geom_point(data = ~ byDayattorneytime %>% filter(StateAbbr == c('TX', 'FL')), aes(
  #   x = EnteredOnUtc,
  #   y = Hours
  # )) +
  facet_wrap(facets =  vars(StateAbbr)) 
```

```{r}
questions%>% 
  filter(
    StateAbbr == c('TX', 'FL','IN','GA','IL'),
    AskedOnUtc > '2020-01-01 12:00:00.000'
    ) %>%
 
  ggplot() +
  geom_histogram(aes(x = AskedOnUtc, alpha = 0.2), bins = 72) +
  geom_histogram(data = . %>% filter(TakenByAttorneyUno != "NULL"), aes(x = AskedOnUtc, fill = StateAbbr), bins = 72)  +
  # geom_point(data = ~ byDayattorneytime %>% filter(StateAbbr == c('TX', 'FL')), aes(
  #   x = EnteredOnUtc,
  #   y = Hours
  # )) +
  facet_wrap(facets =  vars(StateAbbr)) 
```

```{r}

attorneys_data %>%
  filter(
    CreatedUtc > "2020-01-01 00:00:00",
    StateAbbr %in% states_over_2400
  ) %>% 
  ggplot(aes(StateAbbr)) +
  geom_bar()
  
```

```{r}
attorneytimeentries




attorneytimeentries %>%
  filter(
    EnteredOnUtc > "2020-01-01 00:00:00",
    StateAbbr %in% states_over_2400
  ) %>% 
  group_by(StateAbbr, AttorneyUno) %>% 
  summarise(hours = sum(Hours), meanTime = mean(Hours)) %>% 
  arrange(desc(meanTime))


```

```{r}
totalhoursperstate <-
attorneytimeentries %>%
  filter(
    EnteredOnUtc > "2020-01-01 00:00:00",
    StateAbbr %in% states_over_2400
  ) %>% 
  group_by(StateAbbr) %>% 
  summarise(hours = sum(Hours)) %>% 
  arrange(desc(hours))

numAternyPerstate <-
attorneytimeentries %>%
  filter(
    EnteredOnUtc > "2020-01-01 00:00:00",
    StateAbbr %in% states_over_2400
  ) %>% 
  group_by(StateAbbr,AttorneyUno) %>% 
  summarise(numEntriesPerAterny = n())  %>% 
  summarise(numAterny = n()) %>% 
  arrange(desc(numAterny))

numAternyTotattimePerstate <-
  full_join(numAternyPerstate, totalhoursperstate) %>% 
  mutate(
    hoursper = hours / numAterny
  ) %>% 
  arrange(desc(hoursper))
numAternyTotattimePerstate

# numAternyTotattimePerstate %>% 
#   ggplot(aes(numAterny, hours, color = StateAbbr))+
#   geom_point()
df_responses <-
  questions %>% 
  filter(StateAbbr %in% relevant_states, AskedOnUtc >= "2020-01-01 00:00:00") %>%
  group_by(StateAbbr) %>% 
  mutate(
    response_received = 1 * (TakenByAttorneyUno != "NULL")
  ) %>% 
  count(response_received) %>%
  pivot_wider(
    names_from = "response_received",
    names_prefix = "response_",
    values_from = "n"
  ) %>%
  rename(
    responses = response_1,
    nonresponses = response_0
  ) %>%
  mutate(
    total_questions = nonresponses + responses,
    response_rate = responses / total_questions
  ) %>%
  left_join(reporting_policy, by = c("StateAbbr" = "State")) %>%
  left_join(numAternyTotattimePerstate, by = c("StateAbbr" = "State"))
```

```{r}
attorneytimeentries %>%
  filter(
    EnteredOnUtc > "2020-01-01 00:00:00",
    StateAbbr %in% states_over_2400,
    Hours < 40
  ) %>% 
  ggplot() +
  geom_boxplot(aes(StateAbbr, Hours, color = StateAbbr))
```
