---
title: "data"
output: html_document
date: "2023-04-14"
---

```{r}
library(tidyverse)
library(ggplot2)
library(readxl)

```

```{r}
# Glimpse data
attorneys <- read_csv("data/DataFest_2023_Data/attorneys.csv")

attorneytimeentries <- read_csv("data/DataFest_2023_Data/attorneytimeentries.csv")

categories <- read_csv("data/DataFest_2023_Data/categories.csv")

clients <- read_csv("data/DataFest_2023_Data/clients.csv")

questionposts <- read_csv("data/DataFest_2023_Data/questionposts.csv")

questions <- read_csv("data/DataFest_2023_Data/questions.csv")

statesites <- read_csv("data/DataFest_2023_Data/statesites.csv")

subcategories <- read_csv("data/DataFest_2023_Data/statesites.csv")


```
```{r}
questions%>% 
  filter(AskedOnUtc > '2020-01-01 12:00:00.000') %>% 
  group_by(StateAbbr) %>% 
  count() %>% 
  arrange(desc(n))
```
```{r}
attorneytimeentries%>% 
  group_by(StateAbbr) %>% 
  count() %>% 
  arrange(desc(n))
```

```{r}
questions%>% 
  filter(StateAbbr=='FL') %>% 
  group_by(Subcategory) %>% 
  count() %>% 
  arrange(desc(n))
```

```{r}
num_null <- 
  questions %>% 
    filter(TakenByAttorneyUno == "NULL") %>% 
    nrow()

# questions %>% 
#     mutate(is_null = num_null/nrow()) %>% 
#     select(is_null, everything())

questions %>%
  filter(AskedOnUtc > '2020-01-01 12:00:00.000') %>% 
  group_by(StateAbbr) %>%
  mutate(
    is_null = 1 * (TakenByAttorneyUno == "NULL"),
  ) %>%
  count(is_null) %>%
  pivot_wider(
    names_from = "is_null",
    names_prefix = "null",
    values_from = "n"
  ) %>%
  mutate(
    null_percent = null1 / (null0 + null1)
  ) %>% 
  arrange(desc(null_percent))
```
```{r}
  relevant_states %>% 
    group_by(Category) %>%
  mutate(
    is_null = 1 * (TakenByAttorneyUno == "NULL"),
  ) %>%
  count(is_null) %>%
  pivot_wider(
    names_from = "is_null",
    names_prefix = "null",
    values_from = "n"
  ) %>%
  mutate(
    null_percent = null1 / (null0 + null1)
  ) %>% 
  select(null_percent, everything())
```

```{r}
relevant_states <-
  questions %>% 
  group_by(StateAbbr) %>% 
  summarize(start = min(AskedOnUtc)) %>% 
  filter(start < "2020-01-01 00:00:00") %>%
  pull(StateAbbr)

relevant_states
```
```{r}
reporting_data <- read_csv("data/reporting_policy.csv")
```
```{r}
reporting_data
```