---
title: "data"
output: html_document
date: "2023-04-14"
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggrepel)
```

Let's glimpse the datasets to get an overview of what variables we'll be working with.

```{r}
# Glimpse data
attorneys_data <- read_csv("data/DataFest_2023_Data/attorneys.csv")

attorneytimeentries <- read_csv("data/DataFest_2023_Data/attorneytimeentries.csv")

categories <- read_csv("data/DataFest_2023_Data/categories.csv")

clients <- read_csv("data/DataFest_2023_Data/clients.csv")

questionposts <- read_csv("data/DataFest_2023_Data/questionposts.csv")

questions <- read_csv("data/DataFest_2023_Data/questions.csv")

statesites <- read_csv("data/DataFest_2023_Data/statesites.csv")

subcategories <- read_csv("data/DataFest_2023_Data/subcategories.csv")

reporting_policy <- read_csv("data/reporting_policy.csv")
```

Determines list of states with full data since 2020-01-01 and over 2400 questions in that period.

```{r}
states_over_2400 <-
  questions %>%
  group_by(StateAbbr) %>%
  filter(AskedOnUtc >= "2020-01-01 00:00:00") %>% 
  count(StateAbbr) %>%
  filter(n >= 2400) %>%
  pull(StateAbbr)

relevant_states <-
  questions %>% 
  group_by(StateAbbr) %>% 
  summarize(start = min(AskedOnUtc)) %>%
  filter(
    start < "2020-01-01 00:00:00",
    StateAbbr %in% states_over_2400
  ) %>%
  pull(StateAbbr)
```

Tidy data, combine relevant states, reporting policy, and response rates.

```{r}
df_responses <-
  questions %>% 
  filter(StateAbbr %in% relevant_states, AskedOnUtc >= "2020-01-01 00:00:00") %>%
  group_by(StateAbbr) %>% 
  mutate(
    response_received = 1 * (TakenByAttorneyUno != "NULL")
  ) %>% 
  count(response_received) %>%
  pivot_wider(
    names_from = "response_received",
    names_prefix = "response_",
    values_from = "n"
  ) %>%
  rename(
    responses = response_1,
    nonresponses = response_0
  ) %>%
  mutate(
    total_questions = nonresponses + responses,
    response_rate = responses / total_questions
  ) %>%
  left_join(reporting_policy, by = c("StateAbbr" = "State"))
```

```{r}
totalhoursperstate <-
  attorneytimeentries %>%
  filter(
    EnteredOnUtc > "2020-01-01 00:00:00",
    StateAbbr %in% relevant_states
  ) %>% 
  group_by(StateAbbr) %>% 
  summarise(hours = sum(Hours)) %>% 
  arrange(desc(hours))

numAternyPerstate <-
  attorneytimeentries %>%
  filter(
    EnteredOnUtc > "2020-01-01 00:00:00",
    StateAbbr %in% relevant_states
  ) %>% 
  group_by(StateAbbr,AttorneyUno) %>% 
  summarise(numEntriesPerAterny = n())  %>% 
  summarise(numAterny = n()) %>% 
  arrange(desc(numAterny))

numAternyTotattimePerstate <-
  full_join(numAternyPerstate, totalhoursperstate) %>% 
  mutate(
    hoursper = hours / numAterny
  ) %>% 
  arrange(desc(hoursper))
numAternyTotattimePerstate
```

Plot by reporting policy

```{r}
df_responses %>% 
  ggplot() +
  geom_col(aes(
    x = fct_reorder(StateAbbr, response_rate),
    y = response_rate,
    fill = Reporting
  )) +
  ylim(0, 1)
```

```{r}
df_responses %>% 
  left_join(numAternyTotattimePerstate, by = "StateAbbr") %>%
  ggplot(mapping = aes(
    x = hoursper,
    y = response_rate,
    color = StateAbbr
  )) +
  geom_text_repel(
    mapping = aes(label = StateAbbr, color = StateAbbr)
  ) +
  geom_point() +
  ylim(0, 1) +
  xlab("Hours Logged per Active Attorney") +
  ylab("Response Rate (Questions / Questions Taken by Attorney)") +
  ggtitle("Number of Asked Questions vs. Attorney Logged Hours by State") +
  theme(legend.position="none")
```
```{r}
df_responses %>% 
  left_join(numAternyTotattimePerstate, by = "StateAbbr") %>%
  ggplot() +
  geom_point(aes(
    x = numAterny.x,
    y = response_rate,
    color = StateAbbr
  )) +
  ylim(0, 1) +
  xlab("Active Attorney") +
  ylab("Response Rate (Questions / Questions Taken by Attorney)")
```

```{r}
df_responses %>% 
  left_join(numAternyTotattimePerstate, by = "StateAbbr") %>%
  mutate(casePer = total_questions/numAterny.x) %>% 
  ggplot() +
  geom_point(aes(
    x = casePer,
    y = response_rate,
    color = StateAbbr
  )) +
  ylim(0, 1) +
  xlab("Questions Per Active Attorney") +
  ylab("Response Rate (Questions / Questions Taken by Attorney)")
```
