---
title: "brooke"
output: html_document
date: "2023-04-14"
---

```{r}
library(tidyverse)
library(ggplot2)
library(usmap)
library(tidyr)
```

Let's glimpse the datasets to get an overview of what variables we'll be working with.

```{r}
# Glimpse data
attorneys_data <- read_csv("../data/DataFest_2023_Data/attorneys.csv")

glimpse(attorneys_data)

attorneytimeentries <- read_csv("../data/DataFest_2023_Data/attorneytimeentries.csv")

glimpse(attorneytimeentries)

categories <- read_csv("../data/DataFest_2023_Data/categories.csv")

glimpse(categories)

clients <- read_csv("../data/DataFest_2023_Data/clients.csv")

glimpse(clients)

questionposts <- read_csv("../data/DataFest_2023_Data/questionposts.csv")

glimpse(questionposts)

questions <- read_csv("../data/DataFest_2023_Data/questions.csv")

glimpse(questions)

statesites <- read_csv("../data/DataFest_2023_Data/statesites.csv")

glimpse(statesites)

subcategories <- read_csv("../data/DataFest_2023_Data/subcategories.csv")

glimpse(subcategories)
```

```{r}
categories %>%
  group_by(Category) %>%
  summarize()
```

```{r}
questionposts %>%
  filter(str_detect(PostText, "gay")) %>%
  count(StateAbbr) %>%
  arrange(desc(n))

questionposts %>%
  filter(str_detect(PostText, "transgender")) %>%
  left_join(questions, by = "QuestionUno") %>%
  group_by(Category, Subcategory) %>%
  summarize()

questionposts %>%
  filter(str_detect(PostText, "transgender")) %>%
  left_join(questions, by = "QuestionUno") %>%
  count(Subcategory) %>%
  arrange(desc(n))

questions %>%
  filter(Subcategory == "Name Change" | Subcategory == "LGBT Issues") %>%
  count(Subcategory)
```

```{r}
questions %>%
  filter(Category == "Housing and Homelessness") %>%
  count(StateAbbr) %>%
  arrange(desc(n))

```

```{r}
questions %>%
  left_join(clients, by = c("AskedByClientUno" = "ClientUno", "StateAbbr")) %>%
  group_by(StateAbbr) %>%
  mutate(
    is_null = 1 * (TakenByAttorneyUno == "NULL"),
  ) %>%
  count(is_null) %>%
  pivot_wider(
    names_from = "is_null",
    names_prefix = "null",
    values_from = "n"
  ) %>%
  mutate(
    null_percent = null1 / (null0 + null1)
  ) %>%
  # arrange(desc(null_percent)) %>%
  # rename(state = StateAbbr) %>%
  mutate(
    fips = fips(state = StateAbbr, county = County)
  ) %>% 
  plot_usmap(regions = "counties", values = "null_percent", include = c("TX", "FL")) + 
  # labs(title = "US States",
  #      subtitle = "This is a blank map of the counties of the United States.") + 
  scale_fill_continuous(low = "white", high = "red")
  # theme(panel.background = element_rect(color = "black", fill = "lightblue"))
```

```{r}
questions %>%
  left_join(clients, by = c("AskedByClientUno" = "ClientUno", "StateAbbr")) %>%
  group_by(StateAbbr) %>%
  mutate(
    is_null = 1 * (TakenByAttorneyUno == "NULL"),
  ) %>%
  ungroup() %>%
  # group_by(is_null) %>% 
  ggplot() +
  geom_bar(aes(
    x = StateAbbr,
    fill = is_null,
    group = is_null
  ), position = "dodge")
```

```{r}
questions %>%
  filter(StateAbbr %in% c("FL")) %>%
  # filter(!(Category %in% c("Education", "Juvenile", "Income Maintenance"))) %>%
  mutate(
    is_null = 1 * (TakenByAttorneyUno == "NULL"),
  ) %>% 
  # group_by(Category) %>%
  ggplot() +
  geom_freqpoly(aes(AskedOnUtc, color = as.factor(is_null))) +
  facet_wrap(facets = vars(Subcategory))
  # facet_grid(cols = vars(is_null), rows = vars(Category), scales = "free")

questions %>%
  filter(StateAbbr %in% c("TX")) %>%
  # filter(!(Category %in% c("Education", "Juvenile", "Income Maintenance"))) %>%
  mutate(
    is_null = 1 * (TakenByAttorneyUno == "NULL"),
  ) %>% 
  # group_by(Category) %>%
  ggplot() +
  geom_freqpoly(aes(AskedOnUtc, color = as.factor(is_null))) +
  facet_wrap(facets = vars(Subcategory))
  # facet_grid(cols = vars(is_null), rows = vars(Category), scales = "free")
```
